# Generated by Django 4.0.5 on 2022-07-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('nombrecompleto', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='codigoarticulo',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='fechaingreso',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='usuario',
        ),
    ]
