# Generated by Django 4.0.5 on 2022-07-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigoarticulo',
            new_name='codigo',
        ),
    ]
