# Generated by Django 4.0.5 on 2022-07-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_personal_remove_clientes_articulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoarticulo', models.IntegerField()),
                ('articulo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('fechaingreso', models.DateField()),
                ('stock', models.IntegerField()),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
